name: .NET

on:
  push:
  release:
    types:
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Regdata.RPS.Engine.Client
      run: dotnet build --configuration Release --no-restore ./Client/Regdata.RPS.Engine.Client.csproj
    - name: Build Regdata.RPS.Engine.Client NuGet
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ./Client/Regdata.RPS.Engine.Client.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
